name: pphone
description: "A peer-to-peer encrypted calling app"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.1.0
  web_socket_channel: ^3.0.3
  cryptography: ^2.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  clipboard: ^0.1.3
  path_provider: ^2.1.4
  uuid: ^4.5.1
  multicast_dns: ^0.3.2
  collection: ^1.18.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
